package auth.nosy.tech.nosyauth.exception;

public class UserAlreadyExistException extends RuntimeException {
}
